export * from './Contacto';
export * from './XNavbar';
export * from './XXNavbar';
export * from './Presentacion';
export * from './Proyectos';
export * from './SobreMi';
export * from './Tecnologias';
export * from './XProyectos';
export * from './Navbar';